load("//tools/build_rules/verifier_test:cc_indexer_test.bzl", "cc_proto_verifier_test")

cc_proto_verifier_test(
    name = "proto",
    srcs = ["proto.cc"],
    proto_srcs = ["testdata.proto"],
)

# emit_proto_annotation_metadata
